---
- name: Disable OrderController Service Error
  hosts: localhost
  tasks:
    - name: Disable credit card meltdown feature flag
      uri:
        url: "http://easytrade-frontend-easytrade.apps.cluster-t4jgw.dynamic.redhatworkshops.io/feature-flag-service/v1/flags/credit_card_meltdown"
        method: PUT
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          enabled: false
        validate_certs: no
      register: response

    - name: Display result
      debug:
        var: response.status
